FROMGIT: media: ov2740: select regmap
Fix OV2740 build breakage by selecting REGMAP_I2C config:

ov2740.c:1011:23: error: variable has incomplete type 'struct regmap_config'
        struct regmap_config regmap_config = { };
                             ^
ov2740.c:1011:9: note: forward declaration of 'struct regmap_config'
        struct regmap_config regmap_config = { };
               ^
ov2740.c:1028:11: error: implicit declaration of function 'devm_regmap_init_i2c'
        regmap = devm_regmap_init_i2c(client, &regmap_config);

Signed-off-by: Sergey Senozhatsky <sergey.senozhatsky@gmail.com>
Signed-off-by: Sakari Ailus <sakari.ailus@linux.intel.com>
Signed-off-by: Mauro Carvalho Chehab <mchehab+huawei@kernel.org>
(cherry-picked from commit e0f822f8d9698e47cb6781538bc7490fba638979 git://linuxtv.org/media_tree.git)

BUG=none
TEST=Sanity checked basic camera functions

Signed-off-by: Bingbu Cao <bingbu.cao@intel.com>
Change-Id: I3d041c9ca68c3d683666cf710e09a814c93430a2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2544068
Tested-by: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Sergey Senozhatsky <senozhatsky@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Commit-Queue: Sergey Senozhatsky <senozhatsky@chromium.org>