UPSTREAM: drm/amdgpu/display: fix warnings when CONFIG_DRM_AMD_DC_DCN is not set
Properly protect the relevant code with CONFIG_DRM_AMD_DC_DCN.

Fixes: 0b08c54bb7a3 ("drm/amd/display: Fix the display corruption issue on Navi10")
Reviewed-by: Nicholas Kazlauskas <nicholas.kazlauskas@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit e6cd859dc65f19567fdc5e2653cbd543ada2f53c)

Fixes "amdgpu_dm.c:984:34: error: unused variable 'pa_config'" failure.

BUG=b:182126275, b:178566070
TEST=build and boot arm64-generic kernel

Signed-off-by: Praful Swarnakar <praful.swarnakar@amd.corp-partner.google.com>
Change-Id: I0af7db63a1f1cd263255216847eb277fa7f1a25c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2745438
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Commit-Queue: Raul E Rangel <rrangel@chromium.org>