FIXUP: BACKPORT: FROMLIST: media: platform: mtk-isp: Add Mediatek CAM driver
0-day complains about undefined symbols:

ERROR: modpost: "scp_get_device" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_ipi_send" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_put" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_get" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_ipi_unregister" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_ipi_register" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "rproc_shutdown" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "scp_get_rproc" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!
ERROR: modpost: "rproc_boot" [drivers/media/platform/mtk-isp/isp_50/cam/mtk-cam-isp.ko] undefined!

Also, there are dependency warnings:

Kconfig warnings: (for reference only)
   WARNING: unmet direct dependencies detected for MTK_SCP
   Depends on REMOTEPROC && (ARCH_MEDIATEK || COMPILE_TEST

MTK_SCP depends on REMOTEPROC, so anything selecting it depends on
REMOTEPROC as well. Add the missing dependencies.

BUG=b:177195002
TEST=build pass

Change-Id: Ifa0fc8fd2331cc2b42adcec91d5f3809413b7cdf
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3069561
Reviewed-by: Hsin-Yi Wang <hsinyi@chromium.org>
Reviewed-by: Bibby Hsieh <bibby.hsieh@mediatek.com>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>