UPSTREAM: nvme-tcp: get rid of unused helper function
Signed-off-by: Sagi Grimberg <sagi@grimberg.me>
Signed-off-by: Christoph Hellwig <hch@lst.de>
(cherry picked from commit 60141aa08c08a43f3d22626b3a2532106a90a191)

0-day reports:

drivers/nvme/host/tcp.c:209:22: error: unused function 'nvme_tcp_req_offset'

BUG=None
TEST=Build with W=1

Change-Id: I0e740dc19761412eb3a3ba17d85790b3cfaa8085
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3015943
Tested-by: Marty Faltesek <mfaltesek@google.com>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Marty Faltesek <mfaltesek@google.com>
Commit-Queue: Marty Faltesek <mfaltesek@google.com>