FROMGIT: drm/amdgpu: Fix build error reported for some config
drivers/gpu/drm/amd/amdgpu/amdgpu_acpi.c: In function ‘amdgpu_acpi_is_s0ix_active’:
drivers/gpu/drm/amd/amdgpu/amdgpu_acpi.c:1045:32: error: ‘pm_suspend_target_state’ undeclared (first use in this function)
 1045 |                         return pm_suspend_target_state == PM_SUSPEND_TO_IDLE;
      |                                ^~~~~~~~~~~~~~~~~~~~~~~
drivers/gpu/drm/amd/amdgpu/amdgpu_acpi.c:1045:32: note: each undeclared identifier is reported only once for each function it appears in
  CC [M]  drivers/media/usb/dvb-usb/nova-t-usb2.o
  CC [M]  drivers/usb/gadget/legacy/audio.o
  CC [M]  drivers/net/ethernet/intel/igc/igc_tsn.o
  CC [M]  net/mac80211/mlme.o
drivers/gpu/drm/amd/amdgpu/amdgpu_acpi.c:1045:59: error: ‘PM_SUSPEND_TO_IDLE’ undeclared (first use in this function)
 1045 |                         return pm_suspend_target_state == PM_SUSPEND_TO_IDLE;
      |                                                           ^~~~~~~~~~~~~~~~~~
  CC [M]  drivers/usb/gadget/function/f_sourcesink.o
make[4]: *** [scripts/Makefile.build:272: drivers/gpu/drm/amd/amdgpu/amdgpu_acpi.o] Error 1
make[3]: *** [scripts/Makefile.build:515: drivers/gpu/drm/amd/amdgpu] Error 2

Fixes: 69e81db337c1 drm/amdgpu: Check pmops for desired suspend state
Reviewed-by: Aurabindo Pillai <aurabindo.pillai@amd.com>
Signed-off-by: Pratik Vishwakarma <Pratik.Vishwakarma@amd.com>
Signed-off-by: Alex Deucher <alexander.deucher@amd.com>
(cherry picked from commit f2f865cc3c4b9cb78fbc5ffc6abe2f45a245321b https://gitlab.freedesktop.org/agd5f/linux.git amd-staging-drm-next)

BUG=b:193108043
TEST=echo deep > /sys/power/mem_sleep && echo mem > /sys/power/state
    DUT should perform S3 cycle successfully

Change-Id: I4d14029d3f0c7e7f4ff57bef69ee33dba255a195
Signed-off-by: Pratik Vishwakarma <Pratik.Vishwakarma@amd.corp-partner.google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3054906
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Drew Davenport <ddavenport@chromium.org>
Auto-Submit: Pratik Vishwakarma <pratik.vishwakarma@amd.corp-partner.google.com>
Tested-by: Pratik Vishwakarma <pratik.vishwakarma@amd.corp-partner.google.com>
Commit-Queue: Pratik Vishwakarma <pratik.vishwakarma@amd.corp-partner.google.com>