UPSTREAM: EDAC/igen6: fix core dependency
igen6_edac needs mce_register()/unregister() functions,
so it should depend on X86_MCE (or X86_MCE_INTEL).

That change prevents these build errors:

ld: drivers/edac/igen6_edac.o: in function `igen6_remove':
igen6_edac.c:(.text+0x494): undefined reference to `mce_unregister_decode_chain'
ld: drivers/edac/igen6_edac.o: in function `igen6_probe':
igen6_edac.c:(.text+0xf5b): undefined reference to `mce_register_decode_chain'

Fixes: 10590a9d4f23e ("EDAC/igen6: Add EDAC driver for Intel client SoCs using IBECC")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Tony Luck <tony.luck@intel.com>
Link: https://lore.kernel.org/r/20210619160203.2026-1-rdunlap@infradead.org
(cherry picked from commit 0a9ece9ba154dd6205709108180952c55e630833)

BUG=b:193216991
TEST= build and boot on affected platfor

Signed-off-by: George D Sworo <george.d.sworo@intel.com>
Change-Id: Id3a4322a4a851350177f51172176017c1e938f4c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3057145
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Alex Levin <levinale@google.com>
Commit-Queue: Alex Levin <levinale@google.com>