UPSTREAM: drm/modes: add non-OF stub for of_get_drm_display_mode
If CONFIG_OF is disabled, of_get_drm_display_mode is not compiled in,
and drivers using it fail to build:

  ld: drivers/gpu/drm/imx/parallel-display.o: in function `imx_pd_connector_get_modes':
  parallel-display.c:(.text+0x8d): undefined reference to `of_get_drm_display_mode'

Add an inline stub so they can be build-tested with non-OF
configurations.

Reported-by: Randy Dunlap <rdunlap@infradead.org>
Reviewed-by: Daniel Vetter <daniel.vetter@ffwll.ch>
Acked-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Philipp Zabel <p.zabel@pengutronix.de>
(cherry picked from commit 82581fcf070b68a91fb3a3ade08d9a76380a4789)
Signed-off-by: Sean Paul <seanpaul@chromium.org>

BUG=b:187093397
TEST=Tested with single/multiple displays, suspend/resume, hotplugs on volteer/trogdor/dedede/zork, build tested on amd64/arm64-generic

Change-Id: Ic99246bd144b4c1dcc21b8e77c373db300bbfbe8