UPSTREAM: ASoC: codecs: wcd938x: fix uninitialized symbol warnings
This patch fixes below two uninitialized symbol warnings

warning:
	sound/soc/codecs/wcd938x.c:2092 wcd938x_tx_swr_ctrl()
	error: uninitialized symbol 'rate'

	sound/soc/codecs/wcd938x.c:2189 wcd938x_tx_channel_config()
	error: uninitialized symbol 'reg'.

First one my brining in check to already existing if condition and
second one by adding a default switch case to avoid any access to reg.

Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Srinivas Kandagatla <srinivas.kandagatla@linaro.org>
Link: https://lore.kernel.org/r/20210621134502.19537-2-srinivas.kandagatla@linaro.org
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit d245fff1013cb7456ea9ca3f7b858e438c6bbf79)

BUG=b:192352800
TEST=build

Signed-off-by: Judy Hsiao <judyhsiao@chromium.org>
Change-Id: Iaef655bd5b48da54f637a9365e1f23b2925a3325
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2994909
Reviewed-by: Judy Hsiao <judyhsiao@google.com>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Tested-by: Judy Hsiao <judyhsiao@google.com>
Commit-Queue: Judy Hsiao <judyhsiao@google.com>