ASoC: cs40l25: Add missing depends on haptics driver
The ASoC driver calls several functions from the haptics driver, and
thus needs to depend on its presence.

cs40l2x.c:(.text+0x5dc): undefined reference to `cs40l2x_ack_write'
cs40l2x.c:(.text+0x9c4): undefined reference to `cs40l2x_coeff_file_parse'

Change-Id: I051d0b5452120b5468123671970b3f00c28cd727
Signed-off-by: Charles Keepax <ckeepax@opensource.cirrus.com>