FROMGIT: ASoC: mediatek: mt8192: Fix build failure
A build of arm64 allmodconfig with next-20201105 fails with the error:
ERROR: modpost: "mt8192_afe_gpio_request" undefined!
ERROR: modpost: "mt8192_afe_gpio_init" undefined!

Export the symbols so that mt8192-mt6359-rt1015-rt5682.ko finds it.

Signed-off-by: Sudip Mukherjee <sudipm.mukherjee@gmail.com>
Link: https://lore.kernel.org/r/20201105124747.18383-1-sudipm.mukherjee@gmail.com
Signed-off-by: Mark Brown <broonie@kernel.org>
(cherry picked from commit 8bfe8c967546dc05385b52bac49ad972fea5887c
 http://git.kernel.org/pub/scm/linux/kernel/git/broonie/sound.git for-next)

BUG=b:159610020
TEST=boot to shell

Signed-off-by: Jiaxin Yu <jiaxin.yu@mediatek.com>
Change-Id: Ib5714ae5f08b9e27fa643a0e90798c558e0eb787
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2522048
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Nicolas Boichat <drinkcat@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>