BACKPORT: mt76: fix enum type mismatch
There is no 'NONE' version of 'enum mcu_cipher_type', and returning
'MT_CIPHER_NONE' causes a warning:

drivers/net/wireless/mediatek/mt76/mt7921/mcu.c: In function 'mt7921_mcu_get_cipher':
drivers/net/wireless/mediatek/mt76/mt7921/mcu.c:114:24: error: implicit conversion from 'enum mt76_cipher_type' to 'enum mcu_cipher_type' [-Werror=enum-conversion]
  114 |                 return MT_CIPHER_NONE;
      |                        ^~~~~~~~~~~~~~

Add the missing MCU_CIPHER_NONE defintion that fits in here with
the same value.

Fixes: c368362c36d3 ("mt76: fix iv and CCMP header insertion")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20210721150745.1914829-1-arnd@kernel.org

(cherry picked from commit abf3d98dee7c4038152ce88833ddc2189f68cbd4
 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git master)

Conflicts:
   drivers/net/wireless/mediatek/mt76/mt7915/mcu.h
   drivers/net/wireless/mediatek/mt76/mt7921/mcu.h
Backport Notes:
   Just make the driver aligned with upstream

BUG=b:178754244, b:188614537

TEST=Merge patch from upstream

Signed-off-by: Sean Wang <objelf@gmail.com>
Change-Id: Ic36b23c068c2ea51205fcb1eaaa4a018b7297ac7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3156330
Reviewed-by: Joshua Emele <jemele@chromium.org>
Tested-by: Joshua Emele <jemele@chromium.org>
Commit-Queue: Joshua Emele <jemele@chromium.org>