FIXUP: CHROMIUM: drm/i915: Fix spinlock recursion in intel_breadcrumbs
drivers/gpu/drm/i915/gt/intel_breadcrumbs.c:456:16: error: unused variable 'flags'

BUG=chromium:179453336
TEST=Compile with -Werror=unused-variable

Change-Id: Idd51ec47ea5d89aa375950d534ee96ad6c51e738
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2823949
Reviewed-by: Alex Levin <levinale@google.com>