BACKPORT: FROMGIT: rtw88: wow: build wow function only if CONFIG_PM is on
The kernel test robot reports undefined reference after we report wakeup
reason to mac80211. This is because CONFIG_PM is not defined in the testing
configuration file. In fact, functions within wow.c are used if CONFIG_PM
is defined, so use CONFIG_PM to decide whether we build this file or not.

The reported messages are:
   hppa-linux-ld: drivers/net/wireless/realtek/rtw88/wow.o: in function `rtw_wow_show_wakeup_reason':
>> (.text+0x6c4): undefined reference to `ieee80211_report_wowlan_wakeup'
>> hppa-linux-ld: (.text+0x6e0): undefined reference to `ieee80211_report_wowlan_wakeup'

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Ping-Ke Shih <pkshih@realtek.com>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20210728014335.8785-4-pkshih@realtek.com

(cherry picked from commit 05e45887382c4c0f9522515759b34991aa17e69d
 git://git.kernel.org/pub/scm/linux/kernel/git/kvalo/wireless-drivers-next.git master)

Conflicts:
   drivers/net/wireless/realtek/rtw88/Makefile

BUG=b:190570279
TEST=check wowlan mech.

Signed-off-by: Zong-Zhe Yang <kevin_yang@realtek.com>
Change-Id: Idf0ef4207e34fb9d2855c9ef1c0a8acf78e2aa31
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3116207
Reviewed-by: Jintao Lin <jintaolin@chromium.org>
Tested-by: Jintao Lin <jintaolin@chromium.org>
Commit-Queue: Jintao Lin <jintaolin@chromium.org>