FIXUP: FROMGIT: drm/i915/gt: Split logical ring contexts from execlist submission
0-day reports:

drivers/gpu/drm/i915/gt/intel_lrc.c:17:28: error: unused function 'dword_in_page'

Remove the unused function as it serves no purpose.

BUG=b:179453336
TEST=Compile with clang and with -Wunused-function

Change-Id: I80c1ffad781b3eb5380e1ced92b8524677c84460
Disallow-Recycled-Builds: test-failures
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2711481
Reviewed-by: Alex Levin <levinale@google.com>