BACKPORT: mt76: mt7915: fix MESH ifdef block
Fix a build error when CONFIG_MAC80211_MESH is not enabled:

../drivers/net/wireless/mediatek/mt76/mt7915/init.c:47:2: error: expected expression before '}' token
  }, {
  ^

Disallow-Recycled-Builds: test-failures
Fixes: af901eb4ab80 ("mt76: mt7915: get rid of dbdc debugfs knob")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Cc: Shayne Chen <shayne.chen@mediatek.com>
Cc: Ryder Lee <ryder.lee@mediatek.com>
Cc: Lorenzo Bianconi <lorenzo@kernel.org>
Cc: Felix Fietkau <nbd@nbd.name>
Cc: linux-wireless@vger.kernel.org
Cc: Kalle Valo <kvalo@codeaurora.org>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/20201218173202.23159-1-rdunlap@infradead.org
(cherry picked from commit 0bd157fa2aaa2c77d6254321d7751aa9eec68c7b)

Conflicts:
   drivers/net/wireless/mediatek/mt76/mt7915/init.c

BUG=b:178754244, b:188614537
TEST=Build with CONFIG_MAC80211_MESH=n

Change-Id: I84746ba402afeba9eb43de74201d88039421d5a9
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Signed-off-by: Joshua Emele <jemele@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3031405