UPSTREAM: ath11k: fix warning in ath11k_mhi_config
Initialize static variable ath11k_mhi_config for all hw_rev,
return error for unknown hw_rev.
This patch fixes below Smatch warning:
    drivers/net/wireless/ath/ath11k/mhi.c:357 ath11k_mhi_register()
    error: uninitialized symbol 'ath11k_mhi_config'.

Tested-on: QCN9074 hw1.0 PCI WLAN.HK.2.4.0.1-01734-QCAHKSWPL_SILICONZ-1

Fixes: a233811ef600 ("ath11k: Add qcn9074 mhi controller config")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Anilkumar Kolli <akolli@codeaurora.org>
Signed-off-by: Kalle Valo <kvalo@codeaurora.org>
Link: https://lore.kernel.org/r/1617857830-19315-1-git-send-email-akolli@codeaurora.org
(cherry picked from commit ff9f732a87caa5f7bab72bea3aaad58db9b1ac60)

BUG=b:190968626
TEST=build passes

Signed-off-by: Abhishek Kumar <kuabhs@chromium.org>
Change-Id: I404e85921de1f7b441f3f933575835abfd40608d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/2974636
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Reviewed-by: Raul E Rangel <rrangel@chromium.org>