BACKPORT: ASoC: Intel: sof_rt5682: shrink platform_id names below 20 characters
Some Chromebooks machine driver aliases exceed 20 characters, which
leads to sparse warnings:

sound/soc/intel/boards/sof_rt5682.c:959:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:989:25: error: too long
initializer-string for array of char(no space for nul char)

sound/soc/intel/boards/sof_rt5682.c:1039:25: error: too long
initializer-string for array of char(no space for nul char)

Fix by using the 'mx' shortcut for Maxim platforms (already used in
platform firmware)

Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
Reviewed-by: Paul Olaru <paul.olaru@oss.nxp.com>
Reviewed-by: Guennadi Liakhovetski <guennadi.liakhovetski@linux.intel.com>
Reviewed-by: Rander Wang <rander.wang@intel.com>
Link: https://lore.kernel.org/r/20210621194057.21711-4-pierre-louis.bossart@linux.intel.com
Signed-off-by: Mark Brown <broonie@kernel.org>

(cherry picked from commit 590cfb082837cc6c0c595adf1711330197c86a58)

Conflicts:
   sound/soc/intel/boards/sof_rt5682.c

BUG=b:187271853
TEST=Build success on Brya

Signed-off-by: Brent Lu <brent.lu@intel.com>
Change-Id: I58ca315d7b7c159563b48c6b2d08af87482ba61e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3141160
Tested-by: Ajye Huang <ajye_huang@compal.corp-partner.google.com>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Commit-Queue: Curtis Malainey <cujomalainey@chromium.org>